require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Max: 35
  IgnoredMethods: [ 'describe' ]

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

RSpec/DescribeClass:
  Enabled: false
